### ISSUE TITLE
Fixing Travis build

### ISSUE THREAD

**Issue by Blaisorblade** [ernius/formalmetatheory-nominal#2]
I've noticed the build failures and know from experience that fixing those is a pain because of non-deterministic builds with Cabal.

If you're interested in a robust fix, you might want to adapt https://github.com/inc-lc/ilc-agda/blob/master/.travis.yml. For Agda 2.5.1 a good build command should be `stack install --no-terminal --install-ghc --resolver lts-6.2 Agda` (https://github.com/agda/agda/issues/2005#issuecomment-224605338). I understand this is not ideal, but if you're curious I could prepare better instructions. I should do that anyway (background in https://github.com/agda/agda/issues/2005#issuecomment-227411323), but it'd be good to have feedback from a user.

**Comment by ernius** [comment]
Yes I am interested. I would be glad to check your instructions and give you feedback. Thanks in advance !

**Comment by ernius** [comment]
Fixed travis.
